apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ac-brewery-eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
