imageTag: 7.17.3
daemonset:
  extraEnvs:
    - name: "ELASTICSEARCH_HOSTS"
      value: "elastic-master:9200"
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elastic-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elastic-master-credentials
          key: password
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  contains:
                    kubernetes.labels.log_system: "kibana_json"
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
                    exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
                    json.keys_under_root: true
                    json.message_key: message
                    json.add_error_key: true
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
        protocol: https
        ssl.certificate_authorities:
        - /usr/share/filebeat/config/certs/ca.crt
  secretMounts:
    - name: elastic-master-certs
      secretName: elastic-master-certs
      path: /usr/share/filebeat/config/certs
  resources:
    limits:
      # Should avoid OOM (Error 137) when running goss tests into the pod
      memory: "300Mi"

