apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-brewery-inventory-deployment
  labels:
    app: ac-brewery-inventory
    log_system: kibana_json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-brewery-inventory
  template:
    metadata:
      labels:
        app: ac-brewery-inventory
        log_system: kibana_json
    spec:
      containers:
      - name: ac-brewery-inventory
        image: achimiuk/ac-brewery-inventory-service
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{ "spring" : { "artemis": { "host" : "artemis-broker-hdls-svc", "port" : 61616 }, "application": {"name":"inventory-service"},"cloud": {"config": {"fail-fast": "true", "username": "MyUserName", "password": "MySecretPassword", "discovery": {"enabled":  "true", "serviceId": "ac-brewery-config-server"}}}}, "eureka": {"client": {"serviceUrl": {"defaultZone": "http://netflix:eureka@eureka-service:8761/eureka"}, "region": "default", "registerWithEureka" : "true"}, "instance": {"preferIpAddress" : "true"}}}'
        - name: SPRING_PROFILES_ACTIVE
          value: local-discovery,minikube
