version: "3.8"
services:
  jms:
    image: apache/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: achimiuk/mssc-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: achimiuk/ac-brewery-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      SPRING_APPLICATION_JSON: '{"eureka": {"client": {"serviceUrl": {"defaultZone": "http://netflix:eureka@eureka:8761/eureka"}, "region": "default", "registerWithEureka": "true"}, "instance": {"preferIpAddress": "true"}}}'
  inventory-service:
    image: achimiuk/ac-brewery-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - zipkin
    environment:
      SPRING_APPLICATION_JSON: '{ "spring" : { "application": {"name":"inventory-service"},"cloud": {"config": {"fail-fast": "true", "username": "MyUserName", "password": "MySecretPassword", "discovery": {"enabled":  "true", "serviceId": "ac-brewery-config-server"}}}}, "eureka": {"client": {"serviceUrl": {"defaultZone": "http://netflix:eureka@eureka:8761/eureka"}, "region": "default", "registerWithEureka" : "true"}, "instance": {"preferIpAddress" : "true"}}}'
      SPRING_PROFILES_ACTIVE: local-discovery,compose
  order-service:
    image: achimiuk/ac-brewery-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - zipkin
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"application": {"name":"order-service"},"cloud": {"config": {"fail-fast": "true", "username": "MyUserName", "password": "MySecretPassword", "discovery": {"enabled":  "true", "serviceId": "ac-brewery-config-server"}}}}, "eureka": {"client": {"serviceUrl": {"defaultZone": "http://netflix:eureka@eureka:8761/eureka"}, "region": "default", "registerWithEureka" : "true"}, "instance": {"preferIpAddress" : "true"}}}'
      SPRING_PROFILES_ACTIVE: local-discovery,compose
  beer-service:
    image: achimiuk/ac-brewery-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - zipkin
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"application": {"name":"beer-service"}, "cloud": {"config": {"fail-fast": "true", "username": "MyUserName", "password": "MySecretPassword", "discovery": {"enabled":  "true", "serviceId": "ac-brewery-config-server"}}}}, "eureka": {"client": {"serviceUrl": {"defaultZone": "http://netflix:eureka@eureka:8761/eureka"}, "region": "default", "registerWithEureka" : "true"}, "instance": {"preferIpAddress" : "true"}}}'
      SPRING_PROFILES_ACTIVE: local-discovery,compose
