filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              container.labels.collect_logs_with_filebeat: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
logging.metrics.enabled: false
